server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_api_spring_security?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

application:
  security:
    jwt:
      secret-key: n69DEHeJ2LudvSEXQ71QfCXGaAbIJ1l0lOSq2vpsjTKmEZBPowzNZ2QNSkeoJi8X
      expiration: 86400000 # a day
      refresh-token:
        expiration: 14515200000 # 7 deys
